---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: notes-service-secrets
  namespace: notes
spec:
  encryptedData:
    POSTGRES_URI: AgBgAlR0Hrw/gJOhqp27P/b4LjLosX1ccbW+geNzgcUMcN45LFKDnqgifIQKRNefvT6J7obuSmHr1MiPLyz73aryjZBQKfeNY/pQyCTTdCCRS2QY7qr0wG5UxFFdDV+P1ExN06fkNBWrhJM6zEJc55Bn4k2MHBstx6hpDWrrpfZ71dHaNW0F2tmc3QjqhOe7r8zuergswZin5Dou9spjobmYdxWpu3PLhldFWXOgLVRsVfWvch86IM0TaTLtbageO9atqQ57V5/eMZK+M1iI1i45RIwyYblFowAjh6H696auqjxFJu/adLsLkgZ1rA0rw1vRJUAvIR3Dm9QiuTGKgpMzTRl3mJXNFB+Pi/7XelxlGKexNCyC0WB454LugotU+MlVGEHbXmC4xc6PQtw6pjmpvgpfEF7IT3SdkqLgsHIyayFhL8kI5oDMZX1vwfXU/98fh5A8WSXF0xLSAyZAMbo/D7Uw1t6+QlNmKxlyqDx9xoVOmMu1YGD+C4pqS44Jaar01mDMflTt4d8E11ZEU4TOnwaULLBMOU22YLtdXEpFUzfEqby3szbYYmFZrkGIrE3q4+XtLxSTpa86tJrB+oTeHM9mjKRxVdiHV74xoTMhwSCHQsZodBcBL5YQyGJTrqklOUtl+4XLbzxzNUV/q/b18SXNxE6SWa8Jr9fHraQpB+ZDVmHSFyhS9OI4mF7110L4+O6M4OTiTvNJv1kt+GnjJITMvscv3YWY1WxDxy7yjTF123P0htFxQ8tUuFrgA4f9ouPnTrGGXuIo72HunWSce60+4CJDJbTcKjiPcIfvcEJGgPuUp8wa1ljJo4oKVehDbaXTKyDuRcFIREYfxwrPh+dff/Qovn3lcqH610AET4Ai
  template:
    metadata:
      name: notes-service-secrets
      namespace: notes
    type: Opaque
